import { AlgorithmMetadata, AlgorithmType } from '../types/graph';

export const ALGORITHM_METADATA: Record<AlgorithmType, AlgorithmMetadata> = {
  euler: {
    id: 'euler',
    name: 'Euler (Đường đi & Chu trình Euler)',
    shortDesc: 'Duyệt qua mỗi cạnh của đồ thị đúng một lần',
    problem: 'Tìm đường đi hoặc chu trình đi qua mọi cạnh của đồ thị đúng một lần.',
    coreIdea: 'Kiểm tra tính liên thông và bậc của các đỉnh theo định lý Euler. Sử dụng thuật toán Hierholzer hoặc Fleury để xây dựng chu trình/đường đi.',
    timeComplexity: 'O(V + E)',
    spaceComplexity: 'O(V + E)',
    conditions: [
      'Đồ thị phải liên thông (xét trên các đỉnh có bậc > 0).',
      'Chu trình Euler: TẤT CẢ các đỉnh đều có BẬC CHẴN.',
      'Đường đi Euler: Có ĐÚNG 0 hoặc 2 đỉnh có BẬC LẺ (phải bắt đầu ở 1 đỉnh bậc lẻ và kết thúc ở đỉnh bậc lẻ còn lại).',
    ],
    pseudocode: [
      '1. Kiểm tra tính liên thông của đồ thị (BFS / DFS)',
      '2. Đếm số lượng đỉnh bậc lẻ oddCount',
      '3. Nếu oddCount != 0 và oddCount != 2: Trả về "Không tồn tại"',
      '4. Chọn đỉnh xuất phát u (nếu oddCount == 2, u phải là đỉnh bậc lẻ)',
      '5. Khởi tạo ngăn xếp Stack = [u], Tour = []',
      '6. Khi Stack không rỗng:',
      '     Nếu u có đỉnh kề v chưa duyệt cạnh (u, v):',
      '       Đẩy v vào Stack, xóa cạnh (u, v)',
      '     Ngược lại: lấy u ra khỏi Stack, thêm u vào đầu Tour',
      '7. Trả về Tour',
    ],
  },
  hamilton: {
    id: 'hamilton',
    name: 'Hamilton (Đường đi & Chu trình Hamilton)',
    shortDesc: 'Duyệt qua mỗi đỉnh của đồ thị đúng một lần',
    problem: 'Tìm đường đi hoặc chu trình đi qua mọi đỉnh của đồ thị đúng một lần (chu trình phải quay về đỉnh bắt đầu).',
    coreIdea: 'Sử dụng thuật toán quay lui (Backtracking) để duyệt thử tất cả các đường đi khả dĩ. Quay lui khi nhánh thử không còn đỉnh hợp lệ.',
    timeComplexity: 'O(V!) – Bài toán NP-đầy đủ (NP-complete)',
    spaceComplexity: 'O(V) – Độ sâu ngăn xếp đệ quy',
    conditions: [
      'Đồ thị vô hướng hoặc có hướng liên thông.',
      'Định lý Dirac (đủ cho chu trình): Nếu n ≥ 3 và deg(v) ≥ n/2 với mọi v, đồ thị có chu trình Hamilton.',
      'Định lý Ore (đủ cho chu trình): Nếu n ≥ 3 và deg(u) + deg(v) ≥ n với mọi cặp không kề (u, v), đồ thị có chu trình Hamilton.',
    ],
    pseudocode: [
      'Hàm Hamilton(u):',
      '1. Thêm u vào đường đi Path, đánh dấu Visited[u] = true',
      '2. Nếu length(Path) == V:',
      '     Nếu (chế độ Đường đi) hoặc (có cạnh u nối về Start): Thành công!',
      '3. Với mỗi đỉnh kề v của u:',
      '     Nếu Visited[v] == false:',
      '       Gọi đệ quy Hamilton(v)',
      '       Nếu thành công: trả về true',
      '4. Quay lui: Xóa u khỏi Path, Visited[u] = false',
      '5. Trả về false',
    ],
  },
  kruskal: {
    id: 'kruskal',
    name: 'Kruskal (Cây khung nhỏ nhất - MST)',
    shortDesc: 'Xây dựng cây khung bằng cách chọn cạnh có trọng số nhỏ nhất',
    problem: 'Tìm cây khung có tổng trọng số nhỏ nhất trong đồ thị vô hướng có trọng số.',
    coreIdea: 'Chiến lược tham lam (Greedy): Sắp xếp tất cả các cạnh theo trọng số tăng dần. Duyệt từng cạnh, nếu cạnh không tạo chu trình thì nạp vào cây khung (kiểm tra chu trình bằng Disjoint Set Union - DSU).',
    timeComplexity: 'O(E log E) hoặc O(E log V)',
    spaceComplexity: 'O(V) cho cấu trúc Union-Find',
    conditions: [
      'Đồ thị vô hướng, liên thông và có trọng số.',
      'Trọng số cạnh có thể âm hoặc dương.',
      'Cây khung luôn chứa đúng |V| - 1 cạnh.',
    ],
    pseudocode: [
      '1. Sắp xếp danh sách cạnh E theo trọng số tăng dần',
      '2. Khởi tạo cấu trúc Disjoint Set: mỗi đỉnh là một tập riêng biệt',
      '3. MST = [], totalWeight = 0',
      '4. Với mỗi cạnh (u, v) trong danh sách đã sắp xếp:',
      '     Nếu Find(u) != Find(v): // Không tạo chu trình',
      '       Thêm (u, v) vào MST',
      '       Union(u, v)',
      '       totalWeight += w(u, v)',
      '       Nếu length(MST) == V - 1: Dừng thuật toán',
      '5. Trả về MST và totalWeight',
    ],
  },
  prim: {
    id: 'prim',
    name: 'Prim (Cây khung nhỏ nhất - MST)',
    shortDesc: 'Xây dựng cây khung bằng cách mở rộng dần từ một đỉnh',
    problem: 'Tìm cây khung nhỏ nhất bằng cách bắt đầu từ một đỉnh và phát triển dần tập đỉnh của cây.',
    coreIdea: 'Bắt đầu từ đỉnh tùy ý S (tập V_new = {S}). Ở mỗi bước, tìm cạnh nhẹ nhất nối giữa một đỉnh đã thuộc V_new với một đỉnh chưa thuộc V_new, thêm cạnh đó và đỉnh mới vào V_new.',
    timeComplexity: 'O(V^2) với mảng đơn giản hoặc O(E log V) với Min-Heap/Priority Queue',
    spaceComplexity: 'O(V + E)',
    conditions: [
      'Đồ thị vô hướng, liên thông có trọng số.',
      'Hiệu quả vượt trội so với Kruskal trên đồ thị dày (nhiều cạnh, E ≈ V^2).',
      'Cây khung luôn chứa đúng |V| - 1 cạnh.',
    ],
    pseudocode: [
      '1. Chọn đỉnh bắt đầu s, đặt V_new = {s}, MST = []',
      '2. Lặp lại khi |V_new| < |V|:',
      '     Tìm cạnh (u, v) có trọng số nhỏ nhất sao cho:',
      '       u thuộc V_new và v KHÔNG thuộc V_new',
      '     Nếu không tìm thấy: Báo lỗi (đồ thị không liên thông)',
      '     Thêm cạnh (u, v) vào MST',
      '     Thêm đỉnh v vào V_new',
      '3. Trả về MST và tổng trọng số',
    ],
  },
  dijkstra: {
    id: 'dijkstra',
    name: 'Dijkstra (Đường đi ngắn nhất từ một nguồn)',
    shortDesc: 'Tìm đường đi ngắn nhất từ đỉnh nguồn đến mọi đỉnh khác',
    problem: 'Tìm khoảng cách và đường đi ngắn nhất từ đỉnh nguồn S đến đỉnh đích hoặc mọi đỉnh trong đồ thị có trọng số không âm.',
    coreIdea: 'Gán nhãn khoảng cách tạm thời dist[v] = ∞. Mỗi bước chọn đỉnh u chưa chốt có dist[u] nhỏ nhất, chốt đỉnh u, rồi nới lỏng (relax) tất cả các cạnh kề (u, v) theo công thức: dist[v] = min(dist[v], dist[u] + w(u,v)).',
    timeComplexity: 'O(V^2) với mảng hoặc O((V + E) log V) với hàng đợi ưu tiên',
    spaceComplexity: 'O(V + E)',
    conditions: [
      'Đồ thị có hướng hoặc vô hướng.',
      'BẮT BUỘC: Trọng số của TẤT CẢ các cạnh phải KHÔNG ÂM (w(u, v) ≥ 0).',
      'Nếu có trọng số âm, phải dùng Bellman-Ford hoặc Floyd-Warshall.',
    ],
    pseudocode: [
      '1. Khởi tạo: dist[s] = 0, dist[v != s] = vô cùng, prev[v] = null',
      '2. Tập đỉnh chưa chốt Q = V',
      '3. Khi Q không rỗng:',
      '     Chọn u trong Q có dist[u] nhỏ nhất',
      '     Xóa u khỏi Q (Chốt đỉnh u)',
      '     Với mỗi đỉnh kề v của u trong Q:',
      '       alt = dist[u] + w(u, v)',
      '       Nếu alt < dist[v]:',
      '         dist[v] = alt',
      '         prev[v] = u',
      '4. Truy vết đường đi từ đích về nguồn qua mảng prev',
    ],
  },
  compare: {
    id: 'compare',
    name: 'So sánh tổng quan 5 thuật toán đồ thị',
    shortDesc: 'Bảng đối chiếu toàn diện 5 thuật toán trọng tâm trong Toán rời rạc',
    problem: 'Tổng hợp và đối chiếu bài toán, ý tưởng, độ phức tạp và điều kiện áp dụng.',
    coreIdea: 'Giúp sinh viên phân biệt rạch ròi bản chất giữa Euler vs Hamilton, và Kruskal vs Prim vs Dijkstra.',
    timeComplexity: 'N/A',
    spaceComplexity: 'N/A',
    conditions: [],
    pseudocode: [],
  },
};

export const COMPARISON_ROWS = [
  {
    name: 'Euler',
    problem: 'Đường đi / Chu trình Euler',
    targetObject: 'Mỗi CẠNH đúng 1 lần',
    coreIdea: 'Kiểm tra bậc đỉnh & liên thông; thuật toán Hierholzer / Fleury',
    output: 'Dãy các cạnh & đỉnh đi qua toàn bộ cạnh',
    complexity: 'O(V + E)',
    condition: 'Đồ thị liên thông; Chu trình: 0 đỉnh bậc lẻ; Đường đi: đúng 2 đỉnh bậc lẻ',
    graphType: 'Vô hướng / Có hướng, không trọng số',
  },
  {
    name: 'Hamilton',
    problem: 'Đường đi / Chu trình Hamilton',
    targetObject: 'Mỗi ĐỈNH đúng 1 lần',
    coreIdea: 'Thử sai và quay lui (Backtracking), kiểm tra chu trình khép kín',
    output: 'Dãy đỉnh đi qua toàn bộ đỉnh đồ thị',
    complexity: 'O(V!) – NP-complete',
    condition: 'Đồ thị liên thông; thỏa định lý Dirac hoặc Ore (điều kiện đủ)',
    graphType: 'Vô hướng / Có hướng, không trọng số',
  },
  {
    name: 'Kruskal',
    problem: 'Cây khung nhỏ nhất (MST)',
    targetObject: 'Tập hợp CẠNH nhỏ nhất',
    coreIdea: 'Chiến lược Greedy: Sắp xếp cạnh tăng dần, kiểm tra chu trình bằng DSU',
    output: 'Cây khung chứa |V|-1 cạnh có tổng trọng số min',
    complexity: 'O(E log E) = O(E log V)',
    condition: 'Đồ thị vô hướng, liên thông; Trọng số tùy ý',
    graphType: 'Vô hướng, có trọng số',
  },
  {
    name: 'Prim',
    problem: 'Cây khung nhỏ nhất (MST)',
    targetObject: 'Tập hợp ĐỈNH & CẠNH',
    coreIdea: 'Mở rộng dần lát cắt (Cut) từ 1 đỉnh xuất phát bằng cạnh nhẹ nhất',
    output: 'Cây khung chứa |V|-1 cạnh có tổng trọng số min',
    complexity: 'O(V^2) hoặc O(E log V)',
    condition: 'Đồ thị vô hướng, liên thông; Thích hợp đồ thị dày (dense graph)',
    graphType: 'Vô hướng, có trọng số',
  },
  {
    name: 'Dijkstra',
    problem: 'Đường đi ngắn nhất 1 nguồn (SSSP)',
    targetObject: 'Đường đi từ nguồn đến các đỉnh',
    coreIdea: 'Greedy: Chọn đỉnh d(u) nhỏ nhất, nới lỏng (relax) cạnh kề d(v)=min(...)',
    output: 'Cây đường đi ngắn nhất & khoảng cách min từ nguồn',
    complexity: 'O(V^2) hoặc O((V+E) log V)',
    condition: 'Trọng số cạnh BẮT BUỘC KHÔNG ÂM (w ≥ 0)',
    graphType: 'Có hướng / Vô hướng, có trọng số ≥ 0',
  },
];
